[0m11:54:02.466694 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E541AC950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E541AB190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E53B6FC90>]}


============================== 11:54:02.488859 | ced27db9-3f78-45c4-a753-168d547ed329 ==============================
[0m11:54:02.488859 [info ] [MainThread]: Running with dbt=1.7.18
[0m11:54:02.488859 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SureshkumarN\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbt_training', 'send_anonymous_usage_stats': 'True'}
[0m11:54:02.488859 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/SureshkumarN/.dbt')}
[0m11:54:02.488859 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:54:02.488859 [debug] [MainThread]: Starter project path: C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m11:54:02.566941 [info ] [MainThread]: 
Your new dbt project "dbt_training" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:54:02.566941 [info ] [MainThread]: Setting up your profile.
[0m11:54:47.367916 [error] [MainThread]: Encountered an error:

[0m11:54:47.367916 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\cli\main.py", line 516, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m11:54:47.383404 [debug] [MainThread]: Command `dbt init` failed at 11:54:47.383404 after 44.99 seconds
[0m11:54:47.383404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E541A8810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E541F7650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E541F7510>]}
[0m11:54:47.383404 [debug] [MainThread]: Flushing usage events
[0m12:12:03.594188 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026209FE9350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002620941F8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026209FEB6D0>]}


============================== 12:12:03.594188 | 8ff4978a-dac9-4846-b11c-9975f74e45bb ==============================
[0m12:12:03.594188 [info ] [MainThread]: Running with dbt=1.7.18
[0m12:12:03.594188 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\SureshkumarN\\Desktop\\dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:12:03.594188 [info ] [MainThread]: dbt version: 1.7.18
[0m12:12:03.594188 [info ] [MainThread]: python version: 3.11.9
[0m12:12:03.594188 [info ] [MainThread]: python path: C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\python.exe
[0m12:12:03.594188 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m12:12:03.594188 [error] [MainThread]: Encountered an error:
Runtime Error
  Syntax error near line 8
  ------------------------------
  5  |       type: snowflake
  6  |       account: https://ai99815.ap-south-1.aws.snowflakecomputing.com
  7  |       user: sureshkumar
  8  |       password: @7323Sks
  9  | 
  10 |       role: ACCOUNTADMIN
  11 |       database: ANALYTICS
  
  Raw Error:
  ------------------------------
  while scanning for the next token
  found character that cannot start any token
    in "<unicode string>", line 8, column 17
[0m12:12:03.609815 [debug] [MainThread]: Command `dbt debug` failed at 12:12:03.609815 after 0.06 seconds
[0m12:12:03.612677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026209FEBF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026209FEB7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026208E7AFD0>]}
[0m12:12:03.613674 [debug] [MainThread]: Flushing usage events
[0m12:40:58.117737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903A844D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903C008450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903A9C11D0>]}


============================== 12:40:58.117737 | 24c3ed6b-1d8a-4598-bcbd-8befe563128b ==============================
[0m12:40:58.117737 [info ] [MainThread]: Running with dbt=1.7.18
[0m12:40:58.117737 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\SureshkumarN\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:40:58.117737 [info ] [MainThread]: dbt version: 1.7.18
[0m12:40:58.117737 [info ] [MainThread]: python version: 3.11.9
[0m12:40:58.117737 [info ] [MainThread]: python path: C:\Users\SureshkumarN\AppData\Local\Programs\Python\Python311\python.exe
[0m12:40:58.117737 [info ] [MainThread]: os info: Windows-10-10.0.19045-SP0
[0m12:40:58.619279 [info ] [MainThread]: Using profiles dir at C:\Users\SureshkumarN\.dbt
[0m12:40:58.619279 [info ] [MainThread]: Using profiles.yml file at C:\Users\SureshkumarN\.dbt\profiles.yml
[0m12:40:58.619279 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\SureshkumarN\Desktop\dbt\dbt_project.yml
[0m12:40:58.619279 [info ] [MainThread]: adapter type: snowflake
[0m12:40:58.619279 [info ] [MainThread]: adapter version: 1.7.5
[0m12:40:58.619279 [info ] [MainThread]: Configuration:
[0m12:40:58.619279 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m12:40:58.619279 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:40:58.619279 [info ] [MainThread]: Required dependencies:
[0m12:40:58.619279 [debug] [MainThread]: Executing "git --help"
[0m12:40:58.702149 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:40:58.703176 [debug] [MainThread]: STDERR: "b''"
[0m12:40:58.704143 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:40:58.705140 [info ] [MainThread]: Connection:
[0m12:40:58.706165 [info ] [MainThread]:   account: https://ai99815.ap-south-1.aws.snowflakecomputing.com
[0m12:40:58.706165 [info ] [MainThread]:   user: SURESHKUMAR
[0m12:40:58.707134 [info ] [MainThread]:   database: ANALYTICS
[0m12:40:58.708131 [info ] [MainThread]:   warehouse: COMPUTE_WH
[0m12:40:58.709168 [info ] [MainThread]:   role: ACCOUNTADMIN
[0m12:40:58.709168 [info ] [MainThread]:   schema: public
[0m12:40:58.712390 [info ] [MainThread]:   authenticator: None
[0m12:40:58.713387 [info ] [MainThread]:   oauth_client_id: None
[0m12:40:58.714385 [info ] [MainThread]:   query_tag: None
[0m12:40:58.718237 [info ] [MainThread]:   client_session_keep_alive: False
[0m12:40:58.719234 [info ] [MainThread]:   host: None
[0m12:40:58.720230 [info ] [MainThread]:   port: None
[0m12:40:58.721228 [info ] [MainThread]:   proxy_host: None
[0m12:40:58.722224 [info ] [MainThread]:   proxy_port: None
[0m12:40:58.723222 [info ] [MainThread]:   protocol: None
[0m12:40:58.724219 [info ] [MainThread]:   connect_retries: 1
[0m12:40:58.725366 [info ] [MainThread]:   connect_timeout: None
[0m12:40:58.726366 [info ] [MainThread]:   retry_on_database_errors: False
[0m12:40:58.728360 [info ] [MainThread]:   retry_all: False
[0m12:40:58.729358 [info ] [MainThread]:   insecure_mode: False
[0m12:40:58.730773 [info ] [MainThread]:   reuse_connections: None
[0m12:40:58.731772 [info ] [MainThread]: Registered adapter: snowflake=1.7.5
[0m12:40:58.733766 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m12:40:58.734792 [debug] [MainThread]: Using snowflake connection "debug"
[0m12:40:58.734792 [debug] [MainThread]: On debug: select 1 as id
[0m12:40:58.735761 [debug] [MainThread]: Opening a new connection, currently in state init
[0m12:41:09.082794 [debug] [MainThread]: Snowflake adapter: Error running SQL: select 1 as id
[0m12:41:09.082794 [debug] [MainThread]: Snowflake adapter: Rolling back transaction.
[0m12:41:09.082794 [debug] [MainThread]: On debug: No close available on handle
[0m12:41:09.082794 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m12:41:09.082794 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:41:09.089300 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\SureshkumarN\Desktop\dbt\dbt_project.yml> not found

[0m12:41:09.089300 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m12:41:09.094270 [debug] [MainThread]: Command `dbt debug` failed at 12:41:09.094270 after 11.08 seconds
[0m12:41:09.095267 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m12:41:09.096263 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903CE1EE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001903D3CE8D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190368D6410>]}
[0m12:41:09.096263 [debug] [MainThread]: Flushing usage events
